[node]
detect-drivers = false
[[node.driver-configuration]]
max-sessions = 5
display-name = "Firefox windows10"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"93\", \"platformName\": \"WIN10\"}"
[[node.driver-configuration]]
max-sessions = 5
display-name = "Chrome windows10"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"118\", \"platformName\": \"WIN10\"}"
[[node.driver-configuration]]
display-name = "Safari MacOS"
stereotype = "{\"browserName\": \"safari\", \"platformName\": \"MacOS\"}"
[[node.driver-configuration]]
display-name = "IE windows10"
stereotype = "{\"browserName\": \"internet explorer\", \"platformName\": \"WIN10\"}"
#[[node.driver-configuration]]
#display-name = "Opera windows10"
#stereotype = "{\"browserName\":\"operablink\", \"platformName\": \"WIN10\"}"
#[[node.driver-configuration]]
#display-name = "Edge windows10"
#stereotype = "{\"browserName\": \"edge\", \"platformName\": \"WIN10\"}"
